# Process a single image pair
name: HLS_image_correlation_pair
run-name: ${{ inputs.workflow_name }}

# Set workflow input parameters and defaults
on:
  workflow_dispatch:
    inputs:
        img1_date:
            type: string
            required: true
            description: HLS image 1 date
            default: '2016-07-27'
        img2_date:
            type: string
            required: true
            description: HLS image 2 date
            default: '2016-09-25'
        workflow_name:
            description: 'Custom workflow name'
            required: false
            default: 'autoRIFT'
            type: string

  # Must duplicate inputs for workflow_call (https://github.com/orgs/community/discussions/39357)
  workflow_call:
    inputs:
        img1_date:
            type: string
            description: HLS image 1 date
        img2_date:
            type: string
            description: HLS image 2 date
        workflow_name:
            description: 'Custom workflow name'
            type: string

jobs:
    autoRIFT:
        name: ${{ inputs.workflow_name }}
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Conda environment with Micromamba
              uses: mamba-org/setup-micromamba@v2
              with:
                cache-environment: true
                environment-file: environment.yml
            
            - name: Create .netrc for Earthdata
              env: 
                EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
                EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
              run: |
                umask 077
                cat > ~/.netrc <<EOF
                machine urs.earthdata.nasa.gov
                  login ${EARTHDATA_USERNAME}
                  password ${EARTHDATA_PASSWORD}
                EOF
                # curl/GDAL require strict perms; verify:
                ls -l ~/.netrc

            - name: Modify autoRIFT Package
            # current release has deprecated numpy functions https://github.com/nasa-jpl/autoRIFT/issues/97
              run: |
                git clone https://github.com/gbrencher/autoRIFT.git
                cp -f autoRIFT/geo_autoRIFT/autoRIFT/autoRIFT.py /home/runner/micromamba/envs/image-correlation/lib/python3.12/site-packages/autoRIFT/
                
            - name: Download Data and Run autoRIFT Software
              run: |
                python -u scripts/HLS_image_correlation.py ${{ inputs.img1_date }} ${{ inputs.img2_date }}

            - name: Upload Velocity Map as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ inputs.workflow_name }}
                path: |
                    HLS*veloc*.tif
